### ISSUE TITLE
Publish product when backorder is set to "Allow, but notify customer"

### ISSUE THREAD

**Issue by cy-josh** [linksync/woo#1]
I see that you recently updated the product sync to publish products that have their backorder status set to "Allow", but does this work when the product is set to "Allow, but notify customer"?

class-ls-vend-product-helper.php line 124
`if ('yes' == $wooProduct->get_meta()->get_backorders() {`
Should the above become this instead?
`if ('yes' == $wooProduct->get_meta()->get_backorders() || 'notify' == $wooProduct->get_meta()->get_backorders()) {`

Or maybe better yet, use the WooCommerce function `backorders_allowed()` to check all at once?

**Comment by linksyncjameshwartlopez** [comment]
Hi Josh, thank you for you suggestion it is much appreciated. We will be adding that one in the next release :) and yes you are correct that we are only checking 'Allow' for the back orders.

**Comment by cy-josh** [comment]
One other thing to note on this. WooCommerce will not let you add an item with stock status "Out of Stock" to the cart. Can the plugin be adjusted to stop returning the stock status to "out of stock" if it allows backorders?

**Comment by linksyncjameshwartlopez** [comment]
Yep. currently we have that one for allow option only but we will be including allow, notify customer in the next release.

You can view the codes where we set stock status to intstock on class-ls-vend-product-helper.php. Please see the links below. 
https://github.com/linksync/woo/blob/master/includes/apps/vend/helpers/class-ls-vend-product-helper.php#L288

https://github.com/linksync/woo/blob/master/includes/apps/vend/helpers/class-ls-vend-product-helper.php#L680

**Comment by linksyncjameshwartlopez** [comment]
Added on version 2.5.7
